version: '{build}'
clone_folder: c:\projects\caffe2
environment:
  matrix:
    - USE_CUDA: OFF
      CMAKE_BUILD_TYPE: Release

    - USE_CUDA: ON
      CMAKE_BUILD_TYPE: Release

    - USE_CUDA: OFF
      CMAKE_BUILD_TYPE: Debug

    - USE_CUDA: ON
      CMAKE_BUILD_TYPE: Debug

#matrix:
#  allow_failures:
#    - USE_CUDA: ON

install:
- cmd: c:\projects\caffe2\scripts\appveyor\install.bat

build_script:
- cmd: >-
    cd c:\projects\caffe2
    
    git submodule update --init
    
    call scripts\build_windows.bat
